version: 2.1

jobs:
  build:
    docker:
      - image: maven:3.8.4-jdk-11
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Build Project
          command: mvn clean install

      - run:
          name: Run Tests and Generate XML Reports
          command: mvn test

      - store_test_results:
          path: target/surefire-reports/*.xml  # Ajusta la ruta según la configuración de tu proyecto

      - store_artifacts:
          path: target/surefire-reports  # Almacenar informes de pruebas como artefactos
          destination: test-reports

      - store_artifacts:
          path: /tmp/artifacts
          destination: other-artifacts

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
