version: 2.1

jobs:
  build:
    docker:
      - image: maven:3.8.4-jdk-11
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Build Project
          command: mvn clean install

      - run:
          name: Run Tests and Generate XML Reports
          command: mvn test

      - run:
          name: Copy XML Reports
          command: find target/surefire-reports -name "*.xml" -exec cp {} /tmp/artifacts/xml-reports \;

      - store_test_results:
          path: /tmp/artifacts/xml-reports

      - store_artifacts:
          path: /tmp/artifacts/xml-reports
          destination: test-reports

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
