version: 2.1

jobs:
  build:
    docker:
      - image: maven:3.8.4-jdk-11
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Build Project
          command: mvn clean install

      - run:
          name: Run Tests and Generate XML Reports
          command: mvn test

      - run:
          name: Copy XML Reports to Artifacts
          command: cp -R target/surefire-reports /tmp/artifacts

      - store_test_results:
          path: /tmp/artifacts/
          destination: test-results

      - store_artifacts:
          path: /tmp/artifacts/
          destination: test-reports

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
